[package]
name = "c4rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
derive_more = { version = "2.1.1", features = ["full"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
