[package]
name = "c4rs-structurizr-dsl"
version.workspace = true
edition.workspace = true

[dependencies]
c4rs-core = { path = "../c4rs-core" }
serde.workspace = true
thiserror.workspace = true
askama.workspace = true
typed-builder.workspace = true
