[package]
name = "c4rs-structurizr-dsl"
version.workspace = true
edition.workspace = true

[dependencies]
c4rs-core = { path = "../c4rs-core" }
thiserror.workspace = true
askama.workspace = true
bon = "3"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
