[package]
name = "c4rs-structurizr-dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
c4rs-core = { path = "../c4rs-core" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
askama = "0.15"
typed-builder = "0.23"
